package queue

const (
	STORAGE_ROOT_DIR                 = "./data/db"
	STORAGE_PAGES_DIR                = "pages"
	STORAGE_MESSAGE_ID_SIZE          = 16
	STORAGE_HEAP_MAX_SIZE            = 5
	STORAGE_SUBHEAP_LAST_LAYER_NODES = 1 << (STORAGE_HEAP_MAX_SIZE - 1)
	STORAGE_SUBHEAP_NODES            = (1 << STORAGE_HEAP_MAX_SIZE) - 1
	STORAGE_PRIORITY_SIZE_IN_BYTES   = 8
	STORAGE_INDEX_SIZE_IN_BYTES      = 8
	STORAGE_NODE_SIZE_IN_BYTES       = STORAGE_PRIORITY_SIZE_IN_BYTES + STORAGE_INDEX_SIZE_IN_BYTES
	STORAGE_SUBHEAP_SIZE_IN_BYTES    = STORAGE_NODE_SIZE_IN_BYTES * STORAGE_SUBHEAP_NODES
)
